### ISSUE TITLE
Refatorar controle de acesso de facilitadores na aba "Usuários" de administradores, controlando acesso de associações a laboratórios

### ISSUE THREAD

**Issue by brgccf** [brgccf/GestaoResiduosUFPE#39]
Com a mudança recente relacionada a possibilidade de associar-se a mais de um laboratório, É importante permitir que o usuário facilitador consiga acessar o sistema enquanto ele possua alguma associação a algum laboratório registrado. Caso ele perca todos os acessos, então ele perde acesso ao sistema por consequência. 

![image](https://user-images.githubusercontent.com/12815838/29244814-5b1d4a18-7f99-11e7-9fda-ae7c585a8cc0.png)

**Comment by rafaellsma** [comment]
Precisamos conversar sobre essa issue.
